[Server]
  GopherDir = "/var/gopher"
  GopherPort = 70
  Hostname="tunnelchaos.net"
  SearchPort = 7070

[[Events]]
  Name = "39c3"

  [[Events.Infos]]
    Name = "News"
    URL = "https://events.ccc.de/en/category/39c3/feed"
    Type = 0

 [[Events.Infos]]
   Name = "Schedule"
   URL = "https://api.events.ccc.de/congress/2025/schedule.json"
   Type = 2

  [[Events.Infos]]
    Name = "Assemblies"
    URL = "https://api.events.ccc.de/congress/2025/assemblies?format=json"
    Type = 3

  [[Events.Infos]]
    Name = "Schedule Assemblies"
    URL = "https://api.events.ccc.de/congress/2025/events?format=json"
    Type = 4